I2CMux:
  env_a:
    device_type: "si7021"
    address: 0x72
    channel: 2
    params:
      run:
        unit: "f"
      schedule:
        frequency: 2
#   dist_a:
#     device_type: "vl53l0x"
#     address: 0x70
#     channel: 0
#     params:
#       run:
#         unit: "in"
#       schedule:
#         frequency: 3
#   dist_b:
#     device_type: "vl53l0x"
#     address: 0x70
#     channel: 1
#     params:
#       run:
#         unit: "in"
#       schedule:
#         frequency: 3
#   dist_c:
#     device_type: "vl53l0x"
#     address: 0x72
#     channel: 0
#     params:
#       run:
#         unit: "in"
#       schedule:
#         frequency: 1800
#   dist_d:
#     device_type: "vl53l0x"
#     address: 0x72
#     channel: 1
#     params:
#       run:
#         unit: "in"
#       schedule:
#         frequency: 1800

GPIODemux:
  demux_a:
    init:
      gpio_pins_ordered: [25, 23, 24, 17]
      pwr_pin: 27
    devices:
      a:
        index: 0
        device_type: "switch_low"
        params:
          run:
            on_duration: 0.4
            unit: "seconds"
          schedule:
            frequency: 2
      # b:
      #   index: 1
      #   device_type: "switch_low"
      #   params:
      #     run:
      #       on_duration: 0.3
      #       unit: "seconds"
      #     schedule:
      #       frequency: 3
      # c:
      #   index: 2
      #   device_type: "switch_low"
      #   params:
      #     run:
      #       on_duration: 0.1
      #       unit: "seconds"
      #     schedule:
      #       frequency: 1
