I2C:
  env_a:
    device: "si7021"
    address: 0x72
    channel: 2
  dist_a:
    device: "vl53l0x"
    address: 0x70
    channel: 0
  dist_b:
    device: "vl53l0x"
    address: 0x70
    channel: 1
  dist_c:
    device: "vl53l0x"
    address: 0x72
    channel: 0
  dist_d:
    device: "vl53l0x"
    address: 0x72
    channel: 1

my_demux:
  init:
    gpio_pins_ordered: [25, 23, 24, 17]
    pwr_pin: 27
    on_duration: 3.3
  devices:
    a:
      index: 0
      on_duration: 1.7
    b:
      index: 1
      on_duration: 1.3
